### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JustFragger** [ProjectFTS/webwallet_forkattempt#1]
- [ ]  Fully update some stuff in config.js
- [ ]  Need to create API to make web wallet communicate directly with daemon (RPC node)
- [x]  Maybe update old FTS logo to new one if needed. - DONE
